# Generated by Django 5.0.2 on 2024-02-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candiate',
            new_name='Candidate',
        ),
    ]
